# Generated by Django 5.2.5 on 2025-09-18 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.node')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.node')),
            ],
            options={
                'ordering': ['position', 'image__uploaded_at'],
                'unique_together': {('node', 'image')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='core.NodeImage', to='core.image'),
        ),
        migrations.CreateModel(
            name='NodeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.node')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.text')),
            ],
            options={
                'ordering': ['position', 'text__title'],
                'unique_together': {('node', 'text')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='texts',
            field=models.ManyToManyField(blank=True, related_name='nodes', through='core.NodeText', to='core.text'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('parent', 'slug')},
        ),
    ]
